spring:
  application:
  name: tornadosBet
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  primary:
    datasource:
      url: jdbc:mysql://localhost:3306/auth_tornadosbet
      username: root
      password: qwe123qwe123
      driver-class-name: com.mysql.cj.jdbc.Driver
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  secondary:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: qwe
      driver-class-name: org.postgresql.Driver
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: WARN
