spring:
  application:
  name: tornadosBet
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: qwe123qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver
